Document: sample
Title: Debian sample Manual
Author: <insert document author here>
Abstract: This manual describes what sample is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sample/sample.sgml.gz

Format: postscript
Files: /usr/share/doc/sample/sample.ps.gz

Format: text
Files: /usr/share/doc/sample/sample.text.gz

Format: HTML
Index: /usr/share/doc/sample/html/index.html
Files: /usr/share/doc/sample/html/*.html
